import type { Metadata } from "next";
import React from "react";
import Header from "../../components/Header/page";
import Footer from "../../components/Footer/Footer";
import "./globals.scss";
import { Poppins } from "../fonts";
import Provider from "../../Redux/Provider";
import { Locale, i18n } from "../../i18n";
import { getServerSession } from "next-auth";
import SessionProvider from "../../helpers/SessionProvider"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
	params: { lang: Locale };
}

export default async function RootLayout({
	children,
	params: { lang },
}: Readonly<RootLayoutProps>) {
	const session = await getServerSession();

	return (
		<html lang={lang}>
			<body className={Poppins.className}>
				<Provider>
				<SessionProvider session={session}>

						<Header lang={lang} />
						{children}
						<Footer />
						</SessionProvider>
				</Provider>
			</body>
		</html>
	);
}